title       = "goodread"
baseURL     = "https://goodread-cli.tamnd.com/"
description = "A fast, friendly command line for public Goodreads data. One binary that turns books, authors, series, lists, quotes, users, shelves, genres, reviews, and search into rich structured records as table, JSON, JSONL, CSV, TSV, or URLs."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/goodread-cli"
